///////////////////////////////////////////////////////////
//  Logger.cs
//  Implementation of the Class Logger
//  Generated by Enterprise Architect
//  Created on:      23-Aug-2022 22:15:52
//  Original author: Miki
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using productionpkg;
using RVABackend.productionpkg;

namespace productionpkg {
	public class Auth : IAuth {

		public Auth(){

		}

		~Auth(){

		}

		/// 
		/// <param name="username"></param>
		/// <param name="password"></param>
		public Worker Login(string username, string password, WorkerList list){
			Worker worker = WorkerList.m_Worker.Find(w => w.Username.Equals(username) && w.Password.Equals(password));
            if (worker == null)
            {
				return null;
            }
			worker.m_Production = ProductionList.m_Production;
			return worker;
		}

	}//end Logger

}//end namespace productionpkg