///////////////////////////////////////////////////////////
//  CalculateForScholar.cs
//  Implementation of the Class CalculateForScholar
//  Generated by Enterprise Architect
//  Created on:      23-Aug-2022 22:15:52
//  Original author: Miki
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using productionpkg;
namespace productionpkg {
	public class CalculateForScholar : ICalculate {

		public CalculateForScholar(){

		}

		~CalculateForScholar(){

		}

		/// 
		/// <param name="worker"></param>
		public double Calculate(Worker worker, DateTime date){
			double points = 0;
			double salary;

            foreach (Production production in worker.m_Production)
            {
                if (production.Creator.Equals(worker.Username) && production.Date.Year == date.Year && production.Date.Month == date.Month)
                {
					points += production.m_Product.ProductivityPoints * production.Count;
                }
            }

			salary = points * 200;

			return salary;
		}

	}//end CalculateForScholar

}//end namespace productionpkg