///////////////////////////////////////////////////////////
//  ConcreteFactory.cs
//  Implementation of the Class ConcreteFactory
//  Generated by Enterprise Architect
//  Created on:      23-Aug-2022 22:15:52
//  Original author: Miki
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using productionpkg;
namespace productionpkg {
	public class ConcreteFactory : IFactory {

		public ConcreteFactory(){

		}

		~ConcreteFactory(){

		}

		public Product MakeProduct(string type){
			Product product = null;

			switch (type)
			{
				case "Electro":
					product = new ElectricalInstallation();
					break;
				case "Tire":
					product = new Tires();
					break;
				case "Interior":
					product = new Interior();
					break;
				case "Engine":
					product = new Engine();
					break;
				case "MetalWork":
					product = new MetalWork();
					break;
			}
			return product;
		}

	}//end ConcreteFactory

}//end namespace productionpkg