///////////////////////////////////////////////////////////
//  DeleteProductCommand.cs
//  Implementation of the Class DeleteProductCommand
//  Generated by Enterprise Architect
//  Created on:      23-Aug-2022 22:15:52
//  Original author: Miki
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using productionpkg;
using RVABackend.productionpkg;
using RVABackEnd.DataBaseModels;

namespace productionpkg {
	public class DeleteProductCommand : ProductCommand {

		public DeleteProductCommand(){

		}

		~DeleteProductCommand(){

		}

		/// 
		/// <param name="production"></param>
		public override bool Execute(Production production){
			ProductionData productionData = new ProductionData("production");

            if (production != null)
            {
				ProductionList.m_Production.Remove(production);
				//productionData.Remove(production);

				return true;
            }
			return false;
		}

	}//end DeleteProductCommand

}//end namespace productionpkg