///////////////////////////////////////////////////////////
//  Elektroinstalacija.cs
//  Implementation of the Class Elektroinstalacija
//  Generated by Enterprise Architect
//  Created on:      23-Aug-2022 22:15:52
//  Original author: Miki
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using productionpkg;
namespace productionpkg {
	[Serializable]
	public class ElectricalInstallation : Product {

		public ElectricalInstallation(){
			Type = "Electro";
			ProductivityPoints = 3.0;
		}

		~ElectricalInstallation(){

		}

	}//end Elektroinstalacija

}//end namespace productionpkg