///////////////////////////////////////////////////////////
//  Motor.cs
//  Implementation of the Class Motor
//  Generated by Enterprise Architect
//  Created on:      23-Aug-2022 22:15:53
//  Original author: Miki
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using productionpkg;
namespace productionpkg {
	[Serializable]
	public class Engine : Product {

		public Engine(){
			Type = "Engine";
			ProductivityPoints = 5.0;
		}

		~Engine(){

		}

	}//end Motor

}//end namespace productionpkg