///////////////////////////////////////////////////////////
//  IAdmin.cs
//  Implementation of the Interface IAdmin
//  Generated by Enterprise Architect
//  Created on:      23-Aug-2022 22:15:52
//  Original author: Miki
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace productionpkg {
	public interface IAdmin  {

		/// 
		/// <param name="product"></param>
		bool ChangeProduction(Production production, char command);

		/// 
		/// <param name="newWorker"></param>
		bool ChangeWorkerList(Worker newWorker, char command);
	}//end IAdmin

}//end namespace productionpkg