///////////////////////////////////////////////////////////
//  ILogger.cs
//  Implementation of the Interface ILogger
//  Generated by Enterprise Architect
//  Created on:      23-Aug-2022 22:15:52
//  Original author: Miki
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace productionpkg {
	public interface IAuth  {

		/// 
		/// <param name="username"></param>
		/// <param name="password"></param>
		Worker Login(string username, string password, WorkerList list);
	}//end ILogger

}//end namespace productionpkg