///////////////////////////////////////////////////////////
//  ICalculate.cs
//  Implementation of the Interface ICalculate
//  Generated by Enterprise Architect
//  Created on:      23-Aug-2022 22:15:52
//  Original author: Miki
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace productionpkg {
	public interface ICalculate  {

		/// 
		/// <param name="worker"></param>
		double Calculate(Worker worker, DateTime date);
	}//end ICalculate

}//end namespace productionpkg