///////////////////////////////////////////////////////////
//  Enterijer.cs
//  Implementation of the Class Enterijer
//  Generated by Enterprise Architect
//  Created on:      23-Aug-2022 22:15:52
//  Original author: Miki
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using productionpkg;
namespace productionpkg {
	[Serializable]
	public class Interior : Product {

		public Interior(){
			Type = "Interior";
			ProductivityPoints = 1.5;
		}

		~Interior(){

		}

	}//end Enterijer

}//end namespace productionpkg