///////////////////////////////////////////////////////////
//  IProductCommand.cs
//  Implementation of the Interface IProductCommand
//  Generated by Enterprise Architect
//  Created on:      23-Aug-2022 22:15:52
//  Original author: Miki
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace productionpkg {
	public interface IProductCommand  {

		/// 
		/// <param name="production"></param>
		bool Execute(Production production);
	}//end IProductCommand

}//end namespace productionpkg