///////////////////////////////////////////////////////////
//  IScholarInfo.cs
//  Implementation of the Interface IScholarInfo
//  Generated by Enterprise Architect
//  Created on:      23-Aug-2022 22:15:52
//  Original author: Miki
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace productionpkg {
	public interface IScholarInfo  {

		string FacultyName{
			get;
			set;
		}

		string Index{
			get;
			set;
		}
	}//end IScholarInfo

}//end namespace productionpkg