///////////////////////////////////////////////////////////
//  IUser.cs
//  Implementation of the Interface IUser
//  Generated by Enterprise Architect
//  Created on:      23-Aug-2022 22:15:52
//  Original author: Miki
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace productionpkg {
	public interface IUser  {

		string FirstName{
			get;
			set;
		}

		string LastName{
			get;
			set;
		}

		string Password{
			get;
			set;
		}

		string Username{
			get;
			set;
		}
	}//end IUser

}//end namespace productionpkg