///////////////////////////////////////////////////////////
//  IWorkerCommand.cs
//  Implementation of the Interface IWorkerCommand
//  Generated by Enterprise Architect
//  Created on:      23-Aug-2022 22:15:52
//  Original author: Miki
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace productionpkg {
	public interface IWorkerCommand  {

		/// 
		/// <param name="worker"></param>
		bool Execute(Worker worker);
	}//end IWorkerCommand

}//end namespace productionpkg