///////////////////////////////////////////////////////////
//  Limarija.cs
//  Implementation of the Class Limarija
//  Generated by Enterprise Architect
//  Created on:      23-Aug-2022 22:15:52
//  Original author: Miki
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using productionpkg;
namespace productionpkg {
	[Serializable]
	public class MetalWork : Product {

		public MetalWork(){
			Type = "MetalWork";
			ProductivityPoints = 2.5;
		}

		~MetalWork(){

		}

	}//end Limarija

}//end namespace productionpkg