///////////////////////////////////////////////////////////
//  ModifyProductCommand.cs
//  Implementation of the Class ModifyProductCommand
//  Generated by Enterprise Architect
//  Created on:      23-Aug-2022 22:15:53
//  Original author: Miki
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using productionpkg;
using RVABackend.productionpkg;
using RVABackEnd.DataBaseModels;

namespace productionpkg {
	public class ModifyProductCommand : ProductCommand {

		public ModifyProductCommand(){

		}

		~ModifyProductCommand(){

		}

		/// 
		/// <param name="production"></param>
		public override bool Execute(Production production){
			Production check = ProductionList.m_Production.Find(p => p.Id == production.Id);
			ProductionData productionData = new ProductionData("production");

            if (check != null)
            {
				check.m_Product.Type = production.m_Product.Type;
				check.Date = production.Date;
				check.Creator = production.Creator;
				productionData.UpdateFile();
				return true;
            }
			return false;
		}

	}//end ModifyProductCommand

}//end namespace productionpkg