///////////////////////////////////////////////////////////
//  SalaryCalculationForWorker.cs
//  Implementation of the Class SalaryCalculationForWorker
//  Generated by Enterprise Architect
//  Created on:      23-Aug-2022 22:15:53
//  Original author: Miki
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using productionpkg;
namespace productionpkg {
	public class SalaryCalculationForWorker {

		public productionpkg.ICalculate m_ICalculate;

		public SalaryCalculationForWorker(ICalculate calculate){
			m_ICalculate = calculate;
		}

		~SalaryCalculationForWorker(){

		}

		/// 
		/// <param name="worker"></param>
		public double SalaryCalculation(Worker worker, DateTime date){
			return m_ICalculate.Calculate(worker, date);
		}

	}//end SalaryCalculationForWorker

}//end namespace productionpkg