///////////////////////////////////////////////////////////
//  WorkerList.cs
//  Implementation of the Class WorkerList
//  Generated by Enterprise Architect
//  Created on:      23-Aug-2022 22:15:53
//  Original author: Miki
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using productionpkg;
using System.Web;

namespace productionpkg {
	public class WorkerList {

		public static List<Worker> m_Worker = HttpContext.Current.Application["workers"] as List<Worker>;
		public productionpkg.IAuth m_ILogger;

		public WorkerList(IAuth auth){
			m_ILogger = auth;
		}

		~WorkerList(){

		}

		/// 
		/// <param name="username"></param>
		/// <param name="password"></param>
		public Worker Login(string username, string password){
			return m_ILogger.Login(username, password, this);
		}

	}//end WorkerList

}//end namespace productionpkg